;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	electric-newline-and-maybe-indent
	end-of-visual-line
	keyboard-escape-quit
	kill-rectangle
	org-self-insert-command
	org-shiftright
	rectangle-left-char
	rectangle-right-char
	))

(setq mc/cmds-to-run-once
      '(
	))
