;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	custom/rectangular-region-multiple-cursors
	custom/smart-comment
	electric-newline-and-maybe-indent
	end-of-visual-line
	keyboard-escape-quit
	kill-rectangle
	kill-region
	org-backward-sentence
	org-cycle
	org-forward-sentence
	org-meta-return
	org-metaright
	org-self-insert-command
	org-shiftright
	org-yank
	rectangle-left-char
	rectangle-next-line
	rectangle-previous-line
	rectangle-right-char
	))

(setq mc/cmds-to-run-once
      '(
	custom/smart-search
	eval-last-sexp
	mouse-drag-mode-line
	mouse-save-then-kill
	mouse-set-region
	mouse-start-rectangle
	org-ctrl-c-ctrl-c
	swiper
	swiper-mc
	widen
	))
