;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	custom/del-backward
	custom/double-end
	custom/double-home
	custom/nimble-delete-forward
	custom/org-control-return
	custom/org-double-end
	custom/org-double-home
	custom/org-nimble-delete-backward
	custom/org-nimble-delete-forward
	custom/org-undo
	custom/rectangular-region-multiple-cursors
	custom/smart-comment
	custom/smart-mouse-rectangle
	electric-newline-and-maybe-indent
	end-of-visual-line
	keyboard-escape-quit
	kill-rectangle
	kill-region
	org-babel-execute-src-block
	org-backward-sentence
	org-cycle
	org-delete-char
	org-end-of-line
	org-forward-sentence
	org-insert-heading-respect-content
	org-meta-return
	org-metaleft
	org-metaright
	org-self-insert-command
	org-shiftright
	org-yank
	rectangle-left-char
	rectangle-next-line
	rectangle-previous-line
	rectangle-right-char
	))

(setq mc/cmds-to-run-once
      '(
	clm/toggle-command-log-buffer
	counsel-M-x
	custom/double-escape
	custom/nimble-delete-backward
	custom/search-in-region
	custom/smart-search
	custom/swiper-multiple-cursors
	dabbrev-expand
	eval-last-sexp
	mouse-drag-mode-line
	mouse-drag-vertical-line
	mouse-save-then-kill
	mouse-set-region
	mouse-start-rectangle
	org-babel-tangle
	org-ctrl-c-ctrl-c
	org-metadown
	swiper
	swiper-mc
	widen
	))
